djangosige/apps/base/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

from djangosige.configs import DEBUG

app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

if DEBUG:
    urlpatterns += [
        url(r'^404/$', views.handler404),
        url(r'^500/$', views.handler500),
    ]

djangosige/apps/estoque/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'estoque'
urlpatterns = [
    # Consulta de estoque
    #/estoque/consultaestoque/
    url(r'consultaestoque/$', views.ConsultaEstoqueView.as_view(),
        name='consultaestoqueview'),

    # Local de estoque
    #/estoque/local/adicionar/
    url(r'local/saida/adicionar/$',
        views.AdicionarLocalEstoqueView.as_view(), name='addlocalview'),
    #/estoque/local/listalocal
    url(r'local/listalocal/$', views.LocalEstoqueListView.as_view(),
        name='listalocalview'),
    #/estoque/local/editar/
    url(r'local/editar/(?P<pk>[0-9]+)/$',
        views.EditarLocalEstoqueView.as_view(), name='editarlocalview'),

    # Movimento de estoque
    # Lista todos movimentos
    url(r'movimentos/$', views.MovimentoEstoqueListView.as_view(),
        name='listamovimentoestoqueview'),

    # EntradaEstoque
    #/estoque/movimento/adicionarentrada/
    url(r'movimento/adicionarentrada/$',
        views.AdicionarEntradaEstoqueView.as_view(), name='addentradaestoqueview'),
    #/estoque/movimento/listaentradas/
    url(r'movimento/listaentradas/$', views.EntradaEstoqueListView.as_view(),
        name='listaentradasestoqueview'),
    #/estoque/movimento/editarentrada/
    url(r'movimento/editarentrada/(?P<pk>[0-9]+)/$', views.DetalharEntradaEstoqueView.as_view(
    ), name='detalharentradaestoqueview'),

    # SaidaEstoque
    #/estoque/movimento/adicionarsaida/
    url(r'movimento/adicionarsaida/$',
        views.AdicionarSaidaEstoqueView.as_view(), name='addsaidaestoqueview'),
    #/estoque/movimento/listasaidas/
    url(r'movimento/listasaidas/$', views.SaidaEstoqueListView.as_view(),
        name='listasaidasestoqueview'),
    #/estoque/movimento/editarsaida/
    url(r'movimento/editarsaida/(?P<pk>[0-9]+)/$',
        views.DetalharSaidaEstoqueView.as_view(), name='detalharsaidaestoqueview'),

    # TransferenciaEstoque
    #/estoque/movimento/adicionartransferencia/
    url(r'movimento/adicionartransferencia/$',
        views.AdicionarTransferenciaEstoqueView.as_view(), name='addtransferenciaestoqueview'),
    #/estoque/movimento/listatransferencias/
    url(r'movimento/listatransferencias/$', views.TransferenciaEstoqueListView.as_view(),
        name='listatransferenciasestoqueview'),
    #/estoque/movimento/editartransferencia/
    url(r'movimento/editartransferencia/(?P<pk>[0-9]+)/$', views.DetalharTransferenciaEstoqueView.as_view(
    ), name='detalhartransferenciaestoqueview'),
]

djangosige/apps/fiscal/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'fiscal'
urlpatterns = [
    # Nota fiscal saida
    #/fiscal/notafiscal/saida/adicionar/
    url(r'notafiscal/saida/adicionar/$',
        views.AdicionarNotaFiscalSaidaView.as_view(), name='addnotafiscalsaidaview'),
    #/fiscal/notafiscal/saida/listanotafiscal
    url(r'notafiscal/saida/listanotafiscal/$',
        views.NotaFiscalSaidaListView.as_view(), name='listanotafiscalsaidaview'),
    #/fiscal/notafiscal/saida/editar/
    url(r'notafiscal/saida/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalSaidaView.as_view(
    ), name='editarnotafiscalsaidaview'),
    #/fiscal/notafiscal/saida/importar/
    url(r'notafiscal/saida/importar/$',
        views.ImportarNotaSaidaView.as_view(), name='importarnotafiscalsaida'),
    #/fiscal/notafiscal/saida/gerar/
    url(r'notafiscal/saida/gerar/(?P<pk>[0-9]+)/$',
        views.GerarNotaFiscalSaidaView.as_view(), name='gerarnotafiscalsaida'),

    # Nota fiscal entrada
    #/fiscal/notafiscal/entrada/listanotafiscal
    url(r'notafiscal/entrada/listanotafiscal/$',
        views.NotaFiscalEntradaListView.as_view(), name='listanotafiscalentradaview'),
    #/fiscal/notafiscal/entrada/editar/
    url(r'notafiscal/entrada/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalEntradaView.as_view(
    ), name='editarnotafiscalentradaview'),
    #/fiscal/notafiscal/entrada/importar/
    url(r'notafiscal/entrada/importar/$',
        views.ImportarNotaEntradaView.as_view(), name='importarnotafiscalentrada'),

    # Configuracao NF-e
    url(r'notafiscal/configuracaonotafiscal/$',
        views.ConfiguracaoNotaFiscalView.as_view(), name='configuracaonotafiscal'),

    # Natureza operacao
    #/fiscal/naturezaoperacao/adicionar/
    url(r'naturezaoperacao/adicionar/$',
        views.AdicionarNaturezaOperacaoView.as_view(), name='addnaturezaoperacaoview'),
    #/fiscal/naturezaoperacao/listanaturezaoperacao
    url(r'naturezaoperacao/listanaturezaoperacao/$',
        views.NaturezaOperacaoListView.as_view(), name='listanaturezaoperacaoview'),
    #/fiscal/naturezaoperacao/editar/
    url(r'naturezaoperacao/editar/(?P<pk>[0-9]+)/$', views.EditarNaturezaOperacaoView.as_view(
    ), name='editarnaturezaoperacaoview'),

    # Grupo fiscal
    #/fiscal/grupofiscal/adicionar/
    url(r'grupofiscal/adicionar/$',
        views.AdicionarGrupoFiscalView.as_view(), name='addgrupofiscalview'),
    #/fiscal/grupofiscal/listagrupofiscalview
    url(r'grupofiscal/listagrupofiscal/$',
        views.GrupoFiscalListView.as_view(), name='listagrupofiscalview'),
    #/fiscal/grupofiscal/editar/
    url(r'grupofiscal/editar/(?P<pk>[0-9]+)/$',
        views.EditarGrupoFiscalView.as_view(), name='editargrupofiscalview'),

    # Acoes Nota Fiscal
    # Validar XML nota
    url(r'notafiscal/validar/(?P<pk>[0-9]+)/$',
        views.ValidarNotaView.as_view(), name='validarnotafiscal'),
    #/fiscal/notafiscal/emitir/
    url(r'notafiscal/emitir/(?P<pk>[0-9]+)/$',
        views.EmitirNotaView.as_view(), name='emitirnotafiscal'),
    # Clonar nota
    url(r'notafiscal/copiar/(?P<pk>[0-9]+)/$',
        views.GerarCopiaNotaView.as_view(), name='copiarnotafiscal'),
    # Cancelar nota
    url(r'notafiscal/cancelar/(?P<pk>[0-9]+)/$',
        views.CancelarNotaView.as_view(), name='cancelarnotafiscal'),
    # Gerar DANFE
    url(r'notafiscal/gerardanfe/(?P<pk>[0-9]+)/$',
        views.GerarDanfeView.as_view(), name='gerardanfe'),
    # Gerar DANFCE
    url(r'notafiscal/gerardanfce/(?P<pk>[0-9]+)/$',
        views.GerarDanfceView.as_view(), name='gerardanfce'),

    # Comunicacao SEFAZ
    # Consultar cadastro
    url(r'notafiscal/consultarcadastro/$',
        views.ConsultarCadastroView.as_view(), name='consultarcadastro'),
    # Inutilizar notas
    url(r'notafiscal/inutilizarnotas/$',
        views.InutilizarNotasView.as_view(), name='inutilizarnotas'),
    # Consultar nota
    url(r'notafiscal/consultarnota/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    url(r'^notafiscal/consultarnota/(?P<pk>[0-9]+)/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    # Baixar nota
    url(r'notafiscal/baixarnota/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    url(r'^notafiscal/baixarnota/(?P<pk>[0-9]+)/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    # Manifestacao destinatario
    url(r'notafiscal/manifestacaodestinatario/$',
        views.ManifestacaoDestinatarioView.as_view(), name='manifestacaodestinatario'),
]

djangosige/apps/login/urls.py
from django.conf.urls import url
from . import views
#from django.contrib.auth import authenticate

app_name = 'login'
urlpatterns = [
    #/login/
    url(r'^$', views.UserFormView.as_view(), name='loginview'),

    #/login/registrar/
    url(r'registrar/$', views.UserRegistrationFormView.as_view(),
        name='registrarview'),

    #/login/esqueceu/:
    url(r'^esqueceu/$', views.ForgotPasswordView.as_view(), name='esqueceuview'),

    #/login/trocarsenha/:
    url(r'^trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        views.PasswordResetConfirmView.as_view(), name='trocarsenhaview'),

    # logout
    url(r'^logout/$', views.UserLogoutView.as_view(), name='logoutview'),

    #/login/perfil/
    url(r'^perfil/$', views.MeuPerfilView.as_view(), name='perfilview'),

    #/login/editarperfil/
    url(r'^editarperfil/$', views.EditarPerfilView.as_view(), name='editarperfilview'),

    #/login/usuarios/
    url(r'^usuarios/$', views.UsuariosListView.as_view(), name='usuariosview'),

    #/login/usuarios/(id_usuario)
    url(r'usuarios/(?P<pk>[0-9]+)/$',
        views.UsuarioDetailView.as_view(), name='usuariodetailview'),

    # deletar usuario
    url(r'deletaruser/(?P<pk>[0-9]+)/$',
        views.DeletarUsuarioView.as_view(), name='deletarusuarioview'),

    # permissoes usuario
    url(r'permissoesusuario/(?P<pk>[0-9]+)/$',
        views.EditarPermissoesUsuarioView.as_view(), name='permissoesusuarioview'),

    # selecionar empresa
    url(r'selecionarempresa/$', views.SelecionarMinhaEmpresaView.as_view(),
        name='selecionarempresaview'),
]

djangosige/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from .configs.settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djangosige.apps.base.urls')),
    url(r'^login/', include('djangosige.apps.login.urls')),
    url(r'^cadastro/', include('djangosige.apps.cadastro.urls')),
    url(r'^fiscal/', include('djangosige.apps.fiscal.urls')),
    url(r'^vendas/', include('djangosige.apps.vendas.urls')),
    url(r'^compras/', include('djangosige.apps.compras.urls')),
    url(r'^financeiro/', include('djangosige.apps.financeiro.urls')),
    url(r'^estoque/', include('djangosige.apps.estoque.urls')),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

djangosige/apps/cadastro/models/cliente.py
# -*- coding: utf-8 -*-

from django.db import models

from decimal import Decimal

from .base import Pessoa

INDICADOR_IE_DEST = [
    ('1', 'Contribuinte ICMS'),
    ('2', 'Contribuinte isento de Inscrição'),
    ('9', 'Não Contribuinte'),
]


class Cliente(Pessoa):
    limite_de_credito = models.DecimalField(
        max_digits=15, decimal_places=2, default=Decimal('0.00'), null=True, blank=True)
    indicador_ie = models.CharField(
        max_length=1, choices=INDICADOR_IE_DEST, default='9')
    id_estrangeiro = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        verbose_name = "Cliente"

djangosige/apps/cadastro/models/fornecedor.py
# -*- coding: utf-8 -*-

from django.db import models

from .base import Pessoa


class Fornecedor(Pessoa):
    ramo = models.CharField(max_length=64, null=True, blank=True)

    class Meta:
        verbose_name = "Fornecedor"

djangosige/apps/cadastro/models/produto.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal


ORIGEM_ESCOLHAS = (
    (u'0', u'0 - Nacional'),
    (u'1', u'1 - Estrangeira - Importação direta.'),
    (u'2', u'2 - Estrangeira - Adquirida no mercado interno.'),
    (u'3', u'3 - Nacional - Mercadoria ou bem com Conteúdo de Importação superior a 40% e inferior ou igual a 70%.'),
    (u'4', u'4 - Nacional - Cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei nº 288/67, e as Leis nºs 8.248/91, 8.387/91, 10.176/01 e 11.484/ 07'),
    (u'5', u'5 - Nacional - Mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento)'),
    (u'6', u'6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da Resolução CAMEX nº 79/2012 e gás natural'),
    (u'7', u'7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista da Resolução CAMEX nº 79/2012 e gás natural'),
    (u'8', u'8 - Nacional - Mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento).'),
)

TP_OPERACAO_OPCOES = (
    (u'0', u'0 - Entrada'),
    (u'1', u'1 - Saída'),
)

ID_DEST_OPCOES = (
    (u'1', u'1 - Operação interna.'),
    (u'2', u'2 - Operação interestadual.'),
    (u'3', u'3 - Operação com exterior'),
)


class Categoria(models.Model):
    categoria_desc = models.CharField(max_length=32)

    class Meta:
        verbose_name = "Categoria"

    def __unicode__(self):
        s = u'%s' % (self.categoria_desc)
        return s

    def __str__(self):
        s = u'%s' % (self.categoria_desc)
        return s


class Marca(models.Model):
    marca_desc = models.CharField(max_length=32)

    class Meta:
        verbose_name = "Marca"

    def __unicode__(self):
        s = u'%s' % (self.marca_desc)
        return s

    def __str__(self):
        s = u'%s' % (self.marca_desc)
        return s


class Unidade(models.Model):
    sigla_unidade = models.CharField(max_length=3)
    unidade_desc = models.CharField(max_length=16)

    class Meta:
        verbose_name = "Unidade"

    def __unicode__(self):
        s = u'(%s) %s' % (self.sigla_unidade, self.unidade_desc)
        return s

    def __str__(self):
        s = u'(%s) %s' % (self.sigla_unidade, self.unidade_desc)
        return s


class Produto(models.Model):
    # Dados gerais
    codigo = models.CharField(max_length=15)
    codigo_barras = models.CharField(
        max_length=16, null=True, blank=True)  # GTIN/EAN
    descricao = models.CharField(max_length=255)
    categoria = models.ForeignKey(
        Categoria, null=True, blank=True, on_delete=models.PROTECT)
    marca = models.ForeignKey(
        Marca, null=True, blank=True, on_delete=models.PROTECT)
    unidade = models.ForeignKey(
        Unidade, null=True, blank=True, on_delete=models.PROTECT)
    custo = models.DecimalField(max_digits=16, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    venda = models.DecimalField(max_digits=16, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    inf_adicionais = models.CharField(max_length=255, null=True, blank=True)

    # Fiscal
    ncm = models.CharField(max_length=11, null=True,
                           blank=True)  # NCM + EXTIPI
    origem = models.CharField(
        max_length=1, choices=ORIGEM_ESCOLHAS, default='0')
    # Código Especificador da Substituição Tributária
    cest = models.CharField(max_length=7, null=True, blank=True)
    cfop_padrao = models.ForeignKey(
        'fiscal.NaturezaOperacao', null=True, blank=True, on_delete=models.PROTECT)
    grupo_fiscal = models.ForeignKey(
        'fiscal.GrupoFiscal', null=True, blank=True, on_delete=models.PROTECT)

    # Estoque
    estoque_minimo = models.DecimalField(max_digits=16, decimal_places=2, validators=[
                                         MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    estoque_atual = models.DecimalField(max_digits=16, decimal_places=2, validators=[
                                        MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    controlar_estoque = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Produto"

    @property
    def format_unidade(self):
        if self.unidade:
            return self.unidade.sigla_unidade
        else:
            return ''

    def get_sigla_unidade(self):
        if self.unidade:
            return self.unidade.sigla_unidade
        else:
            return ''

    def get_cfop_padrao(self):
        if self.cfop_padrao:
            return self.cfop_padrao.cfop
        else:
            return ''

    def __unicode__(self):
        s = u'%s' % (self.descricao)
        return s

    def __str__(self):
        s = u'%s' % (self.descricao)
        return s

djangosige/apps/cadastro/forms/cliente.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

from djangosige.apps.cadastro.models import Cliente


class ClienteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.fields['limite_de_credito'].localize = True

    class Meta:
        model = Cliente
        fields = ('nome_razao_social', 'tipo_pessoa', 'inscricao_municipal',
                  'limite_de_credito', 'indicador_ie', 'id_estrangeiro', 'informacoes_adicionais', )
        widgets = {
            'nome_razao_social': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_pessoa': forms.RadioSelect(attrs={'class': 'form-control'}),
            'limite_de_credito': forms.TextInput(attrs={'class': 'form-control decimal-mask'}),
            'indicador_ie': forms.Select(attrs={'class': 'form-control'}),
            'inscricao_municipal': forms.TextInput(attrs={'class': 'form-control'}),
            'id_estrangeiro': forms.TextInput(attrs={'class': 'form-control'}),
            'informacoes_adicionais': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome_razao_social': _('Razão Social'),
            'tipo_pessoa': _(''),
            'limite_de_credito': _('Limite de Crédito'),
            'indicador_ie': _('Indicador da IE do Destinatário'),
            'inscricao_municipal': _('Inscrição Municipal'),
            'id_estrangeiro': _('Documento legal (Estrangeiro)'),
            'informacoes_adicionais': _('Informações Adicionais'),
        }

    def save(self, commit=True):
        instance = super(ClienteForm, self).save(commit=False)
        instance.criado_por = self.request.user
        if commit:
            instance.save()
        return instance

djangosige/templates/cadastro/produto/add_popup.html
{%extends 'base/base.html'%}

{%block title%}{{titulo}}{%endblock%}

{%block side_top_bars%}{%endblock%}

{%block content%}
	
	<div class="card">
		<div class="header">
			<h2>{{titulo}}</h2>
		</div>
		<div class="body">
			<form id="popupform" role="form" action="" method="post">
			{% csrf_token %}
				{% for field in form %}
				<div class="form-group">
					<label>{{field.label}}</label>
					{% if field.errors %}<label class="error">{% for error in field.errors %}{{error}}{% endfor %}</label>{% endif %}
					<div class="input-group">
						<div class="form-line">
			      			{{field}}
			      		</div>
		      		</div>
		      	</div>
		    	{% endfor %}
		    	<button class="btn btn-success foot-btn" type="submit"><i class="material-icons">&#xE148;</i><span> SALVAR</span></button>
	    	</form>
    	</div>
   	</div>
	
{%endblock%}

{% block js %}
<script>

	$.Admin.popupwindow.init();

</script>
{% endblock %}

djangosige/templates/cadastro/produto/produto_jsblock.html
{% load staticfiles %}
<!-- JQuery Mask Input Js -->
<script src="{% static 'js/jquery.mask.js' %}"></script>

<!-- JQueryUI autocomplete -->
<link href="{% static 'css/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-ui.min.js' %}"></script>

{% include 'base/tooltip_js.html' %}

<script type="text/javascript">
    var ncm_path = '{% static 'tabelas/ncm/ncm171a.csv' %}'
    var cest_path = '{% static 'tabelas/cest/cest.csv' %}'
    $.Admin.produtoForm.init(ncm_path);
    $.Admin.autocompleteField.autocompleteCest(cest_path);
    $.Admin.maskInput.maskProduto();

</script>

djangosige/templates/cadastro/produto/produto_tab_estoque.html
<div id="estoque_fields">
  <div class="col-sm-12" style="margin-bottom: 17px;margin-top: 5px;">
    {{form.controlar_estoque}}
    <label for="id_controlar_estoque" style="font-weight: bold;" title="Caso selecionado, toda venda/compra deste produto irá gerar automaticamente uma movimentação de estoque.">{{ form.controlar_estoque.label }}</label>
  </div>

  <div class="col-sm-6">
    <div class="form-group">
      <div class="form-line">
        <label>{{form.estoque_minimo.label}}</label>
        {% if form.estoque_minimo.errors %}<label class="error">{% for error in form.estoque_minimo.errors %}{{error}}{% endfor %}</label>{% endif %}
        <div class="select-container">
        {{form.estoque_minimo}}
        </div>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="form-group">
      <label>Qtd. em estoque atual</label>
      <span  style="display:block;font-size:x-large;padding-left:10px;color:#03a9f4;">{% if object.estoque_atual %}{{object.estoque_atual}}{% else %}0,00{% endif %}</span>
    </div>
  </div>

  {% if not object %}
  <div class="col-sm-12">
    <h4 style="border-bottom: 1px solid #afabab;margin-bottom: 25px;">Ajuste de estoque inicial<i class="material-icons" style="font-size:medium;padding-left:10px;" title="Realizar uma movimentação de estoque inicial para este produto, a movimentação poderá ser visualizada no módulo de Estoque > Movimentações de estoque > Entradas">&#xE887;</i></h4>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <div class="form-line">
        <label>{{form.estoque_inicial.label}}</label>
        {% if form.estoque_inicial.errors %}<label class="error">{% for error in form.estoque_inicial.errors %}{{error}}{% endfor %}</label>{% endif %}
        <div class="select-container">
        {{form.estoque_inicial}}
        </div>
      </div>
    </div>
  </div>

   <div class="col-sm-6">
      <div class="form-group">
        <label>{{form.fornecedor.label}}</label>
        {% if form.fornecedor.errors %}<label class="error">{% for error in form.fornecedor.errors %}{{error}}{% endfor %}</label>{% endif %}
        <div class="input-group" style="margin-bottom: 0px;">
          <div class="form-line">
            {{form.fornecedor}}
          </div>
          <a class="input-group-addon newwindow" style="color: green;" title="Adicionar fornecedor" href="{% url 'cadastro:addfornecedorview' %}"><i class="material-icons add-new-icon" title="Adicionar fornecedor">&#xE147;</i></a>
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <label>{{form.local_dest.label}}</label>
        {% if form.local_dest.errors %}<label class="error">{% for error in form.local_dest.errors %}{{error}}{% endfor %}</label>{% endif %}
        <div class="input-group" style="margin-bottom: 0px;">
          <div class="form-line">
            {{form.local_dest}}
          </div>
          <a class="input-group-addon popup" style="color: green;" title="Adicionar localização de estoque" href="{% url 'estoque:addlocalview' %}"><i class="material-icons add-new-icon" title="Adicionar localização de estoque">&#xE147;</i></a>
        </div>
      </div>
    </div>
  {% endif %}

</div>

djangosige/templates/cadastro/produto/produto_tab_fiscal.html
<div class="col-sm-6">
  <div class="form-group">
    <div class="form-line">
      <label>{{form.ncm.label}}</label>
      {% if form.ncm.errors %}<label class="error">{% for error in form.ncm.errors %}{{error}}{% endfor %}</label>{% endif %}
      {{form.ncm}}
    </div>
  </div>
</div>

<div class="col-sm-6">
  <div class="form-group">
    <div class="form-line">
      <label>{{form.origem.label}}</label><strong style="color:red;"> *</strong>
      {% if form.origem.errors %}<label class="error">{% for error in form.origem.errors %}{{error}}{% endfor %}</label>{% endif %}
      <div class="select-container">
      {{form.origem}}
      </div>
    </div>
  </div>
</div>

<div class="col-sm-6">
  <div class="form-group">
    <div class="form-line">
      <label>{{form.cest.label}}</label>
      {% if form.cest.errors %}<label class="error">{% for error in form.cest.errors %}{{error}}{% endfor %}</label>{% endif %}
      {{form.cest}}
    </div>
  </div>
</div>

<div class="col-sm-6">
  <div class="form-group">
  	<label>{{form.cfop_padrao.label}}</label>
    {% if form.cfop_padrao.errors %}<label class="error">{% for error in form.cfop_padrao.errors %}{{error}}{% endfor %}</label>{% endif %}
    <div class="input-group">
	    <div class="form-line">
	      {{form.cfop_padrao}}
	    </div>
	    <a class="input-group-addon newwindow" style="color: green;" title="Adicionar CFOP" href="{% url 'fiscal:addnaturezaoperacaoview' %}"><i class="material-icons add-new-icon" title="Adicionar">&#xE147;</i></a>
    </div>
  </div>
</div>

<div class="col-sm-6">
  <div class="form-group">
  	<label>{{form.grupo_fiscal.label}}</label>
    {% if form.grupo_fiscal.errors %}<label class="error">{% for error in form.grupo_fiscal.errors %}{{error}}{% endfor %}</label>{% endif %}
    <div class="input-group">
	    <div class="form-line">
	      {{form.grupo_fiscal}}
	    </div>
	    <a class="input-group-addon newwindow" style="color: green;" title="Adicionar Grupo Fiscal" href="{% url 'fiscal:addgrupofiscalview' %}"><i class="material-icons add-new-icon" title="Adicionar">&#xE147;</i></a>
    </div>
  </div>
</div>

djangosige/templates/cadastro/produto/produto_tab_list.html
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#tab_dados_gerais" data-toggle="tab">DADOS GERAIS</a></li>
  <li role="presentation"><a href="#tab_estoque" data-toggle="tab">ESTOQUE</a></li>
  <li role="presentation"><a href="#tab_fiscal" data-toggle="tab">FISCAL</a></li>
</ul>